### ISSUE TITLE
Should use Dist::Zilla::Role::PPI

### ISSUE THREAD

**Issue by kentfredric** [plicease/Dist-Zilla-Plugin-OurPkgVersion#1]
I was profiling [Rex](https://metacpan.org/release/Rex) because it had a giant build time ( 3 minutes under NYTProf, oye ), and I discovered one hot-point is in OurPkgVersion re-parsing the whole document with PPI.

![snapshot152](https://cloud.githubusercontent.com/assets/44790/13576511/f209603a-e4f2-11e5-915a-b9318cef52b3.png)

That's that Second bit yellow hierarchy identical to the first :/

Instead, it should use [DZR:PPI](https://metacpan.org/pod/Dist::Zilla::Role::PPI#ppi_document_for_file)

That way, if there's already a cached PPI document, it can just re-use it and re-augment the DOM instead of an expensive reparse.

**Comment by plicease** [comment]
I believe this to be addressed in 0.07.  Please let me know if you find otherwise.
