### ISSUE TITLE
Can we replace :ExecFiles with :PerlExecFiles in the default filefinder?

### ISSUE THREAD

**Issue by stphnlyd** [plicease/Dist-Zilla-Plugin-OurPkgVersion#3]
Since Dist::Zilla 5.038 there comes a new filefinder called :PerlExecFiles
https://metacpan.org/source/RJBS/Dist-Zilla-6.009/Changes#L152

Now this plugin uses :InstallModules and :ExecFiles. :ExecFiles would break if we have non-perl executables under the bin path. So IMHO it makes more sense to use :PerlExecFiles

**Comment by plicease** [comment]
Good idea!

**Comment by plicease** [comment]
Thanks for the patch!  Sending to CPAN as 0.11.
