### ISSUE TITLE
Add quoted version number support/semantic versioning

### ISSUE THREAD

**Issue by glasswalk3r** [plicease/Dist-Zilla-Plugin-OurPkgVersion#6]
Hi,

Any possibility to add a quoted version number, like `our $VERSION = 'v1.0.0'`?

This [post](https://weblog.bulknews.net/how-to-correctly-use-semantic-version-vx-y-z-in-perl-modules-eb08568ab911) explains the idea with a bit more of details.

That should enable OurPkgVersion module support to start using semantic versioning from perl 5.10 and latter.

**Comment by plicease** [comment]
Sorry for not responding sooner.  I don't personally use semantic versions for Perl modules, but I'd accept a patch to add support.

**Comment by glasswalk3r** [comment]
Not a problem. Created PR #12 for that.
I guess that are small enhancements that could be done too:

1. Change the attributes `underscore_eval_version`, `skip_main_module` and `overwrite` to type `Bool`;
2. Implement tests to check if the code `die`s as expected when some setup is done wrong, but that probably will require additional modules to be loaded during the tests ([Test::Exception](https://metacpan.org/pod/Test::Exception), for example).

**Comment by plicease** [comment]
Thanks for making the PR.  I am on vacation atm and won't be back until 20 May.  I don't think it will take long to review the PR, and I'd like to do it the week that I come back.  If I haven't responded by the 27 please feel free to bump this to remind me.

Adding `Test::Exception` is fine.  `Dist::Zilla` tends to have a lot of deps anyway.  Using `eval` and like on `$@` is also fine.

**Comment by glasswalk3r** [comment]
Done that with [this commit](https://github.com/plicease/Dist-Zilla-Plugin-OurPkgVersion/pull/12/commits/4809c35a140cd9d0b955ff2c7f973f73dd8055c4).
