### ISSUE TITLE
Feature Request - replace existing version

### ISSUE THREAD

**Issue by nrdvana** [plicease/Dist-Zilla-Plugin-OurPkgVersion#9]
Did @perlancar ever discuss the version-overwrite feature in [Dist::Zilla::Plugin::PERLANCAR::OurPkgVersion](https://metacpan.org/pod/Dist::Zilla::Plugin::PERLANCAR::OurPkgVersion) with you?

I would like to place a vote for that feature.  One problem I have run into more than once is that I have some code printing or otherwise depending on the version of my own module, and I can't run my tests with a simple ``prove -l`` because the missing versions will cause warnings or exceptions.

I could just use perlancar's module, but I'd prefer to stay with yours for cleaner namespace and more maintenance.

**Comment by plicease** [comment]
No, @perlancar has never attempted to coordinate with me.

I am open to the feature, probably with a property that activates the feature.  A PR would be appreciated.

**Comment by nrdvana** [comment]
I started to work on this, but realized that you are using PPI to get a clean parse, but to capture earlier tokens PERLANCAR just does a direct regex on the file, which could accidentally match within comments or here-doc strings.  I assume you'd like to keep the implementation strictly correct, right?

**Comment by perlancar** [comment]
IIRC I didn't contact @plicease because my version was a quick hack (didn't remember why I replaced PPI with regex). If DZP:OurPkgVersion ends up absorbing this feature, I'll retire DZP:PERLANCAR::OurPkgVersion.

**Comment by nrdvana** [comment]
@perlancar I see exactly why you opted for the "quick hack" :-)  Figuring out how to implement it using PPI took quite a bit of extra thinking.

**Comment by plicease** [comment]
I believe this to be resolved by #10, thanks!

**Comment by nrdvana** [comment]
Thanks for the quick turnaround!
